### ISSUE TITLE
Set up NPM and TypeScript

### ISSUE THREAD

**Issue by jdunkerley** [jdunkerley/TechStudio#3]

**Comment by nowen** [comment]
You have subscribed the wrong Nick Owen.

On Thu, Nov 12, 2015 at 6:46 AM, James Dunkerley <notifications@github.com>
wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jdunkerley/TechStudio/issues/3>.
>



-- 
Nick Owen  --  WiKID Systems, Inc.
http://www.wikidsystems.com
Commercial/Open Source Two-Factor Authentication
http://twitter.com/wikidsystems | #wikid on freenode.net
Get our low-volume newsletter - Notices, updates : http://eepurl.com/zzUeP

**Comment by owennw** [comment]
You are not currently subscribed, at least in a way that we can do anything about it :)
