### ISSUE TITLE
Which httpserver?

### ISSUE THREAD

**Issue by jdunkerley** [jdunkerley/TechStudio#9]
Use the standard http-server of use the live-server that Angular 2 uses?

**Comment by jdunkerley** [comment]
I vote for live-server

**Comment by owennw** [comment]
Are we talking about https://www.npmjs.com/package/http-server vs https://www.npmjs.com/package/gulp-live-server ?

**Comment by owennw** [comment]
I've set it up to use gulp-live-server. I'll close the issue now, feel free to reopen if you prefer a different solution.
